### ISSUE TITLE
[ENHANCEMENT] replacing chromium with direct http

### ISSUE THREAD

**Issue by MGThePro** [Wamy-Dev/Rezi#3]
Title says it all. Shipping chromium makes the whole project very bloated, unorganized and windows-only.
Now, this might not be possible for every site due to DDOS protection or captchas, but at least on some sources it should work without any issues, allowing at least a partial transition, and other sources could always be picked in the future for better support of parsing html directly via http.

**Comment by Wamy-Dev** [comment]
This may be true, and it may be windows-only, but that would mean scrapping most of what we have down. I will consider this, but this would be a huge step, for something mostly minor.
