### ISSUE TITLE
[BUG] Results bug

### ISSUE THREAD

**Issue by Bleh97** [Wamy-Dev/Rezi#4]
![image](https://user-images.githubusercontent.com/101638946/160300120-c4ad4fd2-9dc0-4190-ba5b-2ee291c11418.png)

**Comment by Wamy-Dev** [comment]
Thank you. This bug is the result of there not being enough results. Basically, if there aren't enough links to fill the lines of the embed, it gives this error. I will be fixing it soon with a check to make sure there are enough links to fill the embed.

**Comment by Wamy-Dev** [comment]
> Thank you. This bug is the result of there not being enough results. Basically, if there aren't enough links to fill the lines of the embed, it gives this error. I will be fixing it soon with a check to make sure there are enough links to fill the embed.

 I will close this bug when it gets fixed.

**Comment by Wamy-Dev** [comment]
![image](https://i.imgur.com/7wixjEX.png)
Changed it to not be a scary looking error, will make it base64 here in a couple days.

**Comment by Wamy-Dev** [comment]
This is with one result. Same thing with up to 4 total. Just creates a new embed.
![1 result](https://i.imgur.com/EEflqog.png)
No result response. 
![no result](https://i.imgur.com/IK9ZrLj.png)

Fixed in [this commit](https://github.com/Wamy-Dev/Rezi/commit/7d2fad510e867d89948b30095f89f46df3a4e942)
